# Written according to this guide:
# https://makefiletutorial.com/
# also i used this one:
# https://www.gnu.org/software/make/manual/html_node/Text-Functions.html

NAME := SpectrumAnalyzer

SRCS_DIR := Src
BUILD_DIR := Build
LINKER := stm32f446xe_flash.ld

C_SRCS := $(wildcard $(SRCS_DIR)/*.c)
S_SRCS := $(wildcard $(SRCS_DIR)/*.S)

OBJ := $(patsubst $(SRCS_DIR)/%.c, $(BUILD_DIR)/%.o, $(C_SRCS))
OBJ += $(patsubst $(SRCS_DIR)/%.S, $(BUILD_DIR)/%.o, $(S_SRCS))

INC_FLAGS := -I. #has to be a dot cause if i pass in Inc as a folder it looks for Inc folder in Inc folder and it doesnt exist XD

CPU_FLAGS := -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard	-mlittle-endian #copied that one from 
#cmake/gnu-tools-for-stm32.cmake(old file that was pregenerated by the stm32cube extension),
#also in the same file mthmub is added after other flags, for their respective cpus, are set

#GREAT NEEEEWSS, my system is also little-endian, so there are no problems in communication via UART(cause both send LSB first)

GCC_FLAGS := -fdata-sections -ffunction-sections -O0 -g3 -Wall -Wextra -std=gnu2x

CFLAGS := $(CPU_FLAGS) $(GCC_FLAGS) $(INC_FLAGS)

LINKER_FLAGS := $(CPU_FLAGS) -T	$(LINKER) -Wl,--gc-sections --specs=nano.specs 

.DELETE_ON_ERROR:
all: $(BUILD_DIR)/$(NAME).bin
$(BUILD_DIR)/$(NAME).elf: $(OBJ)
	arm-none-eabi-gcc $(OBJ) $(LINKER_FLAGS) -o $@
	arm-none-eabi-size $@

$(BUILD_DIR)/$(NAME).bin: $(BUILD_DIR)/$(NAME).elf
	arm-none-eabi-objcopy -O binary $< $@

$(BUILD_DIR)/%.o: $(SRCS_DIR)/%.c
	@mkdir -p $(dir $@)
#idk what it does, i just tabbed and its there
	arm-none-eabi-gcc -c $(CFLAGS) $< -o $@ 

$(BUILD_DIR)/%.o: $(SRCS_DIR)/%.S
	@mkdir -p $(dir $@)
#tabbed again XD
	arm-none-eabi-gcc -c $(CFLAGS) $< -o $@ 







