/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#define STM32F446xx
#include <stdint.h>
#include "Inc/stm32f4xx.h"

void delay_ms(uint16_t ms)
{
    for(volatile uint16_t i = 0; i <= ms * 4000; i++);
}

int main(void)
{
    /* Loop forever */
	while(1)
    {
        GPIOA->ODR ^= (1 << 5);
        delay_ms(500);
    }
}

